#!/bin/bash
# Usage: __kubernetes_cluster_tmux <filter> <iterm_profile> <prompt> [pattern...]

FILTER="$1"
ITERM_PROFILE="$2"
SELECTION_PROMPT="$3"
shift 3
PATTERN=$(echo "$*" | sed 's/ /.*/g')

TEMP_LIST_FILE=$(mktemp)
kubectl config get-contexts -o name | grep "$FILTER" | grep -E -i "${PATTERN}" > "${TEMP_LIST_FILE}" || true

if [[ "$(wc -l < "${TEMP_LIST_FILE}")" -eq "0" ]]; then
  echo "No environments found to match the given filter: [$*]" >&2
  exit 1
elif [[ "$(wc -l < "${TEMP_LIST_FILE}")" -eq "1" ]]; then
  CONTEXT=$(cat "${TEMP_LIST_FILE}")
else
  set -euo pipefail
  CONTEXT=$(cat "${TEMP_LIST_FILE}" | fzf --prompt="$SELECTION_PROMPT")
fi

rm -f "${TEMP_LIST_FILE}"

${HOME}/.iterm2/it2profile -s "$ITERM_PROFILE"
printf "\e]1337;SetBadgeFormat=%s\a" "$(echo -n "${CONTEXT}" | base64)"

set -euo pipefail

SESSION="${CONTEXT}"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then
  TL=$(tmux new-session -d -s "$SESSION" -n main -P -F '#{pane_id}')

  WIN_W=$(tmux display-message -t "$SESSION:main" -p '#{window_width}')
  WIN_H=$(tmux display-message -t "$SESSION:main" -p '#{window_height}')

  TOP_LEFT_W=$(( WIN_W * 35 / 100 ))
  BOT_LEFT_W=$(( WIN_W * 1 / 100 ))
  TOP_H=$(( WIN_H / 2 ))

  BL=$(tmux split-window -v -t "$TL" -P -F '#{pane_id}')
  tmux resize-pane -t "$TL" -y "$TOP_H"

  TR=$(tmux split-window -h -t "$TL" -P -F '#{pane_id}')
  tmux resize-pane -t "$TL" -x "$TOP_LEFT_W"

  BR=$(tmux split-window -h -t "$BL" -P -F '#{pane_id}')
  tmux resize-pane -t "$BL" -x "$BOT_LEFT_W"

  tmux send-keys -t "$TL" ". set_kubernetes_context $CONTEXT && k9s --context $CONTEXT -n beacon -c pods" C-m
  tmux send-keys -t "$BL" ". set_kubernetes_context $CONTEXT && k9s --context $CONTEXT -n beacon -c flinkdeployments.flink.apache.org" C-m
  tmux send-keys -t "$TR" ". set_kubernetes_context $CONTEXT" C-m
  tmux send-keys -t "$BR" ". set_kubernetes_context $CONTEXT" C-m

  tmux select-pane -t "$TL"
fi

tmux attach -t "$SESSION"

${HOME}/.iterm2/it2profile -s "Default"
printf "\e]1337;SetBadgeFormat=%s\a" "$(echo -n "" | base64)"
