#!/bin/bash

PATTERN=$(echo $* | sed 's/ /\.\*/g')

SORTED_PROFILES=$(mktemp)
TEMP_LIST_FILE=$(mktemp)

yq -p ini -o tsv 'keys | .[] | select(. == "profile *") | sub("^profile ", "")' ~/.aws/config > ${SORTED_PROFILES}

cat ${SORTED_PROFILES} | grep -E -i "^${PATTERN}$" > ${TEMP_LIST_FILE}
cat ${SORTED_PROFILES} | grep -E -i "${PATTERN}" | grep -E -i -v "^${PATTERN}$" >> ${TEMP_LIST_FILE}

if [[ "$(cat "${TEMP_LIST_FILE}" | wc -l)" -eq "1" ]]
then
	AWS_PROFILE=$(cat "${TEMP_LIST_FILE}")
else
	AWS_PROFILE=$(cat "${TEMP_LIST_FILE}" | fzf --preview '_aws_profile_fzf_preview {}')
fi

export AWS_PROFILE
