#!/bin/bash

PATTERN=$(echo $* | sed 's/ /\\.\\*/g')

TEMP_LIST_FILE=$(mktemp)

cat ~/.aws/config | egrep '^\[profile.*' | tr -d '[]' | sed 's|^profile ||' | grep -E -i "^${PATTERN}$" > ${TEMP_LIST_FILE}
cat ~/.aws/config | egrep '^\[profile.*' | tr -d '[]' | sed 's|^profile ||' | grep -E -i "${PATTERN}" | grep -E -i -v "^${PATTERN}$" | sort >> ${TEMP_LIST_FILE}

if [[ "$(cat "${TEMP_LIST_FILE}" | wc -l)" -eq "1" ]]
then
	SELECTED_PROFILE=$(cat "${TEMP_LIST_FILE}")
else
	SELECTED_PROFILE=$(cat "${TEMP_LIST_FILE}" | fzf --preview '_aws_profile_fzf_preview {}')
fi

rm -f "${TEMP_LIST_FILE}"

if [[ -n "${SELECTED_PROFILE}" ]]
then
	eval "$(aws-vault export "${SELECTED_PROFILE}" --format export-env)"
fi
