#!/bin/bash

help() { 
    if [ -z "${SCRIPT}" ];
    then
        SCRIPT=$(basename "$0")
    fi
    printf "\n"
    printf "Connects to Beacon PSQL DBs\n"
    printf "\n"
    printf "Usage:\n"
    printf "\t%s <environment>\n" "${SCRIPT}"
    printf "\n"
    printf "Options:\n"
    printf "\n"
    printf "<environment>:\n"
    printf "\tThe name of the environment.\n"
    printf "\n"
    printf "Examples:\n"
    printf "\t# Connect to Dev\n"
    printf "\t%s dev \n" "${SCRIPT}"
    printf "\n"
    exit 1
}

SCRIPT_DIR=$(dirname "$0")
CONFIG_FILE="${SCRIPT_DIR}/bdb.conf"
SELECTION_PROMPT="Choose DB > "

PATTERN=$(echo $* | sed 's/ /\.\*/g')

TEMP_LIST_FILE=$(mktemp)

cat ${CONFIG_FILE} | grep -v '^#' | cut -d',' -f1 | grep -E -i "${PATTERN}" > ${TEMP_LIST_FILE}

if [[ "$(cat "${TEMP_LIST_FILE}" | wc -l)" -eq "0" ]] 
then
  echo "No DB found to match the given filter: [$*]" >&2
  exit 1
elif [[ "$(cat "${TEMP_LIST_FILE}" | wc -l)" -eq "1" ]]
then
	ENV_NAME=$(cat "${TEMP_LIST_FILE}")
else
  set -euo pipefail
	ENV_NAME=$(cat "${TEMP_LIST_FILE}" |  fzf --prompt="$SELECTION_PROMPT" --with-nth=1 --preview "cat ${CONFIG_FILE} | grep ^{}, | awk -F',' '{ printf \"DB Server : %s\nPort      : %s\nDB Name   : %s\n\", \$2, \$3, \$4 }'")
fi

LINE=$(cat "${CONFIG_FILE}" | egrep "^${ENV_NAME},")

IFS=',' read -r ENVIRONMENT DB_SERVER DB_PORT DB_NAME USERNAME PASSWORD_FILE<<<"$LINE"

echo "Connecting to ${ENV_NAME}"

psqlenv --workspace-name "db--${ENV_NAME}" --db-server ${DB_SERVER} --db-port ${DB_PORT} --db-name ${DB_NAME} --username ${USERNAME} --password-file ${PASSWORD_FILE}
