# environment, workspace, aws_profile, aws_region
soju,soju-dev,prod-soju,us-west-2
campari,campari-dev,prod-campari,eu-west-1
champagne,champagne-dev,prod-champagne,us-east-1
appletini,appletini-dev,prod-appletini,us-east-1
limoncello,limoncello-dev,prod-limoncello,us-east-1
rum,rum-dev,prod-rum,us-west-2
triple-sec,triple-sec-dev,prod-triple-sec,us-east-1
underberg,underberg-dev,prod-underberg,eu-west-1
