#!/bin/bash

CLUSTER_NAME="production"
PROJECT_DIR="/Users/ronk/code/work/beacon-security/"
SELECTION_PROMPT="Choose Production Cluster > "

PATTERN=$(echo $* | sed 's/ /.*/g')

TEMP_LIST_FILE=$(mktemp)

kubectl config get-contexts -o name | grep prod | grep -E -i "${PATTERN}" > ${TEMP_LIST_FILE}

if [[ "$(cat "${TEMP_LIST_FILE}" | wc -l)" -eq "0" ]]
then
  echo "No environments found to match the given filter: [$*]" >&2
  exit 1
elif [[ "$(cat "${TEMP_LIST_FILE}" | wc -l)" -eq "1" ]]
then
	CONTEXT_NAME=$(cat "${TEMP_LIST_FILE}")
else
  set -euo pipefail
	CONTEXT_NAME=$(cat "${TEMP_LIST_FILE}" | fzf --prompt="$SELECTION_PROMPT")
fi

CLUSTER_ARN=$(kubectl config get-contexts "${CONTEXT_NAME}" --no-headers | awk '{print $3}')
AWS_REGION=$(echo "${CLUSTER_ARN}" | awk -F: '{print $4}')
AWS_PROFILE=$(cat ~/.kube/config | yq ".users[] | select(.name == \"${CLUSTER_ARN}\") | .user.exec.env[] | select(.name == \"AWS_PROFILE\") | .value")
WORKSPACE="${CONTEXT_NAME}"

${HOME}/.iterm2/it2profile -s "kubernetes-cluster"
printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "${WORKSPACE}" | base64)

eks \
  --workspace-name "$WORKSPACE" \
  --aws-region "$AWS_REGION" \
  --aws-profile "$AWS_PROFILE" \
  --cluster-name "$CLUSTER_NAME" \
  --project-dir "$PROJECT_DIR"

printf "\e]1337;SetBadgeFormat=%s\a" $(echo -n "" | base64)
