# environment, workspace, aws_profile, aws_region
soju,soju-prod,prod-soju,us-west-2
campari,campari-prod,prod-campari,eu-west-1
champagne,champagne-prod,prod-champagne,us-east-1
appletini,appletini-prod,prod-appletini,us-east-1
limoncello,limoncello-prod,prod-limoncello,us-east-1
rum,rum-prod,prod-rum,us-west-2
triple-sec,triple-sec-prod,prod-triple-sec,us-east-1
underberg,underberg-prod,prod-underberg,eu-west-1
